### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by krishnadubey** [rexcardan/Evil-DICOM#42]
Hi,

I'm using latest version of Evil-DICOM-1.5.1.2. it is giving "Arithmetic operation resulted in an overflow." error when using large dcm file.
can you please share new version with fix of this error.

**Comment by rexcardan** [comment]
Can you try the newest Evil DICOM v 1.5.1.4 on NuGet or download the most recent Git repo? I have had that error before with non compliant DICOM files where for some reason, the nested private tags in a sequence are written as Explicit VR instead of Implicit VR as specified in their transfer syntax. If this is all too technical, don't worry about it. Try again and let me know if it doesn't work.
